export interface Task {
  id: number;
  description: string;
  status: 'pending' | 'completed' | 'not-done';
  groupHomeId: number;
  residentId?: number;
  completedAt?: string;
  completedBy: number;
  createdAt: string;
  updatedAt: string;
}

export interface CompletedTask {
  /**
   * Primary key generated by Postgres for each completion row.
   * DO NOT send this from the client – let the DB create it.
   */
  id?: number;

  /**
   * Foreign‑key reference to the template task (`tasks.id`)
   * that this completion entry corresponds to. **Required.**
   */
  taskId: number;

  description: string;
  status: 'pending' | 'completed' | 'not-done';
  groupHomeId: number;
  residentId?: number;

  /**
   * Exact timestamp of when the user ticked the task.
   * Must be sent from the client.
   */
  completedAt?: string;

  /**
   * Calendar date used for the unique (taskId, completedDate) index.
   * Optional – omit to let the DB default CURRENT_DATE fill it.
   */
  completedDate?: string;

  completedBy: number;
  createdAt?: string;
  updatedAt?: string;
  reason?: string;
}

export type TaskInsert = Omit<Task, 'id' | 'createdAt' | 'updatedAt' | 'completedBy'>;
